# Starter pipeline
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: 'select * from fr.fram_acc limit 1;'
    ServerName: 'mysql-rfam-public.ebi.ac.uk'
    DatabaseName: 'Rfam'
    SqlUsername: 'rfamro'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml